<?php

namespace Database\Seeders;

use App\Models\Complaint;
use App\Models\ComplaintCategory;
use App\Models\Recipient;
use App\Models\Student;
use App\Models\Ticket;
use App\Models\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Arr;
use Illuminate\Support\Collection;
use Illuminate\Support\Str;

class AnalyticsSeeder extends Seeder
{
    public function run(): void
    {
        $admin = User::query()->firstWhere('role', User::ROLE_SDS_ADMIN);

        $recipients = Recipient::query()->with('user')->get();
        if ($recipients->isEmpty()) {
            $recipients = collect();
            foreach (range(1, 3) as $index) {
                $user = User::create([
                    'name' => 'Recipient ' . $index,
                    'username' => 'recipient' . $index,
                    'email' => 'recipient' . $index . '@example.com',
                    'password' => bcrypt('password'),
                    'must_change_password' => false,
                    'role' => User::ROLE_RECIPIENT,
                    'is_active' => true,
                    'email_verified_at' => now(),
                ]);

                $recipients->push(Recipient::create([
                    'user_id' => $user->id,
                    'staff_id' => 'REC' . str_pad($index, 3, '0', STR_PAD_LEFT),
                    'department' => 'Department ' . $index,
                    'designation' => 'Officer',
                ]));
            }
        }

        $categories = ComplaintCategory::query()->limit(5)->get();
        if ($categories->isEmpty()) {
            foreach ($recipients->take(5) as $index => $recipient) {
                $categories->push(ComplaintCategory::create([
                    'name' => 'Category ' . ($index + 1),
                    'description' => 'Autogenerated category for analytics.',
                    'recipient_id' => $recipient->id,
                    'resolution_deadline_days' => 5 + $index,
                    'is_active' => true,
                ]));
            }
        }

        $students = Student::query()->with('user')->limit(20)->get();
        if ($students->isEmpty()) {
            $students = collect();
            foreach (range(1, 20) as $index) {
                $user = User::create([
                    'name' => 'Student ' . $index,
                    'username' => 'student' . $index,
                    'email' => 'student' . $index . '@example.com',
                    'password' => bcrypt('password'),
                    'must_change_password' => false,
                    'role' => User::ROLE_STUDENT,
                    'is_active' => true,
                    'email_verified_at' => now(),
                ]);

                $students->push(Student::create([
                    'user_id' => $user->id,
                    'student_id' => 'STU' . str_pad($index, 4, '0', STR_PAD_LEFT),
                    'department' => 'Department ' . ($index % 4 + 1),
                    'course' => 'Course ' . ($index % 3 + 1),
                    'year_level' => (string) (($index % 4) + 1),
                    'block' => 'Block ' . chr(65 + ($index % 4)),
                ]));
            }
        }

        $statuses = [
            Ticket::STATUS_PENDING,
            Ticket::STATUS_ASSIGNED,
            Ticket::STATUS_IN_PROGRESS,
            Ticket::STATUS_ESCALATED,
            Ticket::STATUS_RESOLVED,
            Ticket::STATUS_CLOSED,
        ];

        $months = collect(range(1, 6));
        $count = 0;

        foreach ($months as $month) {
            foreach (range(1, 8) as $index) {
                $student = $students->random();
                $category = $categories->random();
                $complaintDate = now()->subMonths(rand(0, 5))->subDays(rand(0, 28));

                $complaint = Complaint::create([
                    'reference_number' => Complaint::generateReferenceNumber(),
                    'student_id' => $student->id,
                    'category_id' => $category->id,
                    'subject_title' => 'Complaint ' . Str::random(6),
                    'personnel_involved' => 'Staff ' . Str::random(4),
                    'description' => 'Auto-generated complaint for analytics seeder.',
                    'is_anonymous' => false,
                    'created_at' => $complaintDate,
                    'updated_at' => $complaintDate,
                ]);

                $status = Arr::random($statuses);
                $resolvedAt = null;
                $closedAt = null;
                $ticketCreatedAt = $complaintDate->copy()->addHours(1);
                $timeline = collect([]);

                if ($status === Ticket::STATUS_PENDING) {
                    $timeline->push(['status' => Ticket::STATUS_PENDING, 'at' => $ticketCreatedAt]);
                }

                if ($status === Ticket::STATUS_ASSIGNED) {
                    $timeline->push(['status' => Ticket::STATUS_ASSIGNED, 'at' => $ticketCreatedAt]);
                }

                if ($status === Ticket::STATUS_IN_PROGRESS) {
                    $timeline->push(['status' => Ticket::STATUS_ASSIGNED, 'at' => $ticketCreatedAt]);
                    $timeline->push(['status' => Ticket::STATUS_IN_PROGRESS, 'at' => $ticketCreatedAt->copy()->addDays(1)]);
                }

                if ($status === Ticket::STATUS_ESCALATED) {
                    $timeline->push(['status' => Ticket::STATUS_ASSIGNED, 'at' => $ticketCreatedAt]);
                    $timeline->push(['status' => Ticket::STATUS_ESCALATED, 'at' => $ticketCreatedAt->copy()->addDays(2)]);
                }

                if ($status === Ticket::STATUS_RESOLVED) {
                    $resolvedAt = $ticketCreatedAt->copy()->addDays(rand(1, 6));
                    $timeline->push(['status' => Ticket::STATUS_ASSIGNED, 'at' => $ticketCreatedAt]);
                    $timeline->push(['status' => Ticket::STATUS_IN_PROGRESS, 'at' => $ticketCreatedAt->copy()->addDay()]);
                    $timeline->push(['status' => Ticket::STATUS_RESOLVED, 'at' => $resolvedAt]);
                }

                if ($status === Ticket::STATUS_CLOSED) {
                    $resolvedAt = $ticketCreatedAt->copy()->addDays(rand(1, 5));
                    $closedAt = $resolvedAt->copy()->addDays(rand(1, 3));
                    $timeline->push(['status' => Ticket::STATUS_ASSIGNED, 'at' => $ticketCreatedAt]);
                    $timeline->push(['status' => Ticket::STATUS_IN_PROGRESS, 'at' => $ticketCreatedAt->copy()->addDay()]);
                    $timeline->push(['status' => Ticket::STATUS_RESOLVED, 'at' => $resolvedAt]);
                    $timeline->push(['status' => Ticket::STATUS_CLOSED, 'at' => $closedAt]);
                }

                Ticket::create([
                    'complaint_id' => $complaint->id,
                    'status' => $status,
                    'assigned_to' => $recipients->random()->user_id,
                    'current_handler_id' => $recipients->random()->user_id,
                    'deadline' => $complaintDate->copy()->addDays($category->resolution_deadline_days),
                    'acknowledged_at' => $ticketCreatedAt->copy()->addHours(3),
                    'resolved_at' => $resolvedAt,
                    'closed_at' => $closedAt,
                    'created_at' => $ticketCreatedAt,
                    'updated_at' => $timeline->last()['at'] ?? $ticketCreatedAt,
                ]);

                $count++;
                if ($count >= 50) {
                    break 2;
                }
            }
        }
    }
}
